spring:
  application:
    name: taigongthtm-project
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':               # 匹配所有请求
            allowedOrigins: "*"  #跨域处理 允许所有的域
            allowedMethods:      # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 215MB

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.43.158.100:3306/hyh_project?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

file:
  prefix: F:\files\

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


---
spring:
  profiles: dev
server:
  port: 8088

---
spring:
  profiles: test
server:
  port: 8089


---
spring:
  profiles: pro
server:
  port: 8090


